
import json
from llms import BaseLlm
from tools.code_executor import CodeExecutorTool
from tools.code_writer import CodeWriterTool

class ExecutorAgent:
    """
    The Executor Agent is responsible for writing, testing, and debugging code
    based on a structured plan.
    """

    def __init__(self, llm: BaseLlm):
        self.llm = llm
        self.code_executor = CodeExecutorTool()
        self.code_writer = CodeWriterTool()
        self.generated_code_snippets = {}

    async def execute_plan(self, plan: dict) -> dict:
        """
        Executes the code generation and testing phase based on the plan.

        Args:
            plan: The structured JSON plan from the Planner Agent.

        Returns:
            A dictionary of nodeId -> generated_code.
        """
        print("\n--- Executor Agent ---")

        if "customCode" not in plan or not plan["customCode"]:
            print("No custom code to generate. Executor finished.")
            return {}

        for code_task in plan["customCode"]:
            node_id = code_task["nodeId"]
            language = code_task["language"]
            prompt = code_task["prompt"]

            print(f"\nGenerating code for node: '{node_id}'...")

            # Construct the prompt for the executor LLM
            code_generation_prompt = f"""
You are an expert {language} developer. Your task is to write a function that fulfills the following request.
Respond ONLY with the raw code, without any markdown formatting, explanations, or example usage.

**Request:**
{prompt}
"""
            
            # Call the LLM to generate the code
            # We are still using the mocked Claude LLM
            generated_code = await self.llm.generate_content(code_generation_prompt)
            print(f"--- Code Generated by LLM ---\n{generated_code}\n-----------------------------")

            # --- Start of the Debugging Loop ---
            max_retries = 3
            for i in range(max_retries):
                print(f"\n--- Debugging Attempt {i + 1}/{max_retries} ---")
                
                # Step 1: Execute the code
                execution_result = self.code_executor.execute(language, generated_code)
                stdout = execution_result["stdout"]
                stderr = execution_result["stderr"]

                # Step 2: Check for errors
                if not stderr:
                    print("Code executed successfully!")
                    print(f"Output:\n{stdout}")
                    self.generated_code_snippets[node_id] = generated_code
                    break  # Exit loop if code is valid
                
                print(f"Execution failed. Error:\n{stderr}")

                # Step 3: If there are errors, construct a new prompt to fix them
                if i < max_retries - 1:
                    print("Attempting to fix the code...")
                    fix_prompt = f"""
You are an expert {language} developer. The following code that you previously generated has an error. 
Please fix it.

**Original Request:**
{prompt}

**Broken Code:**
```javascript
{generated_code}
```

**Error Message:**
```
{stderr}
```

Respond ONLY with the raw, corrected code, without any markdown formatting, explanations, or example usage.
"""
                    generated_code = await self.llm.generate_content(fix_prompt)
                    print(f"--- Code Regenerated by LLM ---\n{generated_code}\n-----------------------------")
                else:
                    print("Max retries reached. Unable to fix the code.")
                    self.generated_code_snippets[node_id] = f"// FAILED TO GENERATE VALID CODE\n{generated_code}"
                    break
            # --- End of the Debugging Loop ---
        
        print("\nExecutor Agent finished generating all code snippets.")
        return self.generated_code_snippets
